# Generated by Django 4.0.5 on 2022-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_bio_profile_id_user_profile_profileimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='First_name',
            field=models.CharField(default='0000000', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_name',
            field=models.CharField(default='0000000', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='workingat',
            field=models.CharField(default='0000000', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.jpg', upload_to='profile_images'),
        ),
    ]
