# Generated by Django 4.0.5 on 2022-06-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='First_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Last_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workingat',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
