# Generated by Django 4.0.5 on 2022-06-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workingat',
        ),
        migrations.AlterField(
            model_name='profile',
            name='First_name',
            field=models.TextField(max_length=50),
        ),
    ]
