# Generated by Django 4.0.5 on 2022-06-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_profile_last_name_remove_profile_workingat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='First_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='workingat',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
