# Generated by Django 4.0.5 on 2022-06-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_last_name_profile_lastname_profile_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workingat',
            field=models.TextField(max_length=20),
        ),
    ]
